### ISSUE TITLE
Error when using elementDicts.py

### ISSUE THREAD

**Issue by yoyo1989** [nyusngroup/SESNspectraLib#21]
I encountered SyntaxError:

```
[yuqianliu@Yuqians-MacBook-Air SESNspectraLib]$ python Ic_conv_Icbl_MCMC.py 10qts_20100815_Lick_3-m_v1-z.flm-flat.csv 0 Fe
Traceback (most recent call last):
  File "Ic_conv_Icbl_MCMC.py", line 46, in <module>
    from elementDicts import *
  File "/Users/yuqianliu/github_rep/SESNspectraLib/elementDicts.py", line 12
    X0 = {'Fe' : np.array([4200, 4800, 5000, 5600], 'min' : 4500, 'max': 5100)}
                                                          ^
SyntaxError: invalid syntax
```

Then I changed     **X0 = {'Fe' : np.array([4200, 4800, 5000, 5600], 'min' : 4500, 'max': 5100)}**
 to     **X0 = {'Fe' : np.array([4200, 4800, 5000, 5600]), 'min' : 4500, 'max': 5100}**

Then there is IndexError: 

```
yuqianliu@Yuqians-MacBook-Air SESNspectraLib]$ python Ic_conv_Icbl_MCMC.py 10qts_20100815_Lick_3-m_v1-z.flm-flat.csv 0 Fe
Working with element:  Fe
reading inputs...
running convolution...


Element: Fe, Phase: 0, input spectrum: 10qts_20100815_Lick_3-m_v1-z.flm-flat.csv
Traceback (most recent call last):
  File "Ic_conv_Icbl_MCMC.py", line 451, in <module>
    if conv(obsSpec, templSpec, element) == -1:
  File "Ic_conv_Icbl_MCMC.py", line 407, in conv
    if y_flat[x_flat < X0[element]['min']].mean() and \
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

```

I think the error is still in elementDicts.py, but couldn't figure it out. Thanks!

**Comment by fedhere** [comment]
fixed it, and i removed some more hardcoded 'Fe' please check that there are no more
